version: '3.8'

services:
  # Serviço para o contêiner PHP
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
      # Mapeia o diretório "app" do host para o diretório "/var/www/symfony_docker" no contêiner

  # Serviço para o contêiner Nginx
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
      # Mapeia a porta 8080 do host para a porta 80 no contêiner Nginx
    volumes:
      - ./app:/var/www/symfony_docker
      # Mapeia o diretório "app" do host para o diretório "/var/www/symfony_docker" no contêiner Nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # Mapeia o arquivo de configuração "default.conf" do host para o diretório "/etc/nginx/conf.d/default.conf" no contêiner Nginx
    depends_on:
      - php
      # Define uma dependência do serviço Nginx no serviço PHP. Isso significa que o serviço PHP será iniciado antes do serviço Nginx. 
